### ISSUE TITLE
[Question] Keeping up with official KCauldron updates?

### ISSUE THREAD

**Issue by iKaneki-Ken** [TCPR/KCauldron#12] opened 2016-01-18 16:24 UTC
It this fork also implementing the latest KCauldron updates as well?

**Comment by Yive** [comment] 2016-01-18 17:39
Yes, but since the most recent commit is an experimental feature, I didn't think it was worth adding just yet.

**Comment by iKaneki-Ken** [comment] 2016-01-18 18:19
No, it's not, it's causing a few issues, if possible, would you or someone who has access to edit the code be able to remove the following commit?

https://gitlab.prok.pw/KCauldron/KCauldron/commit/b53d579e350cf2305c4f5ec901ef24808e1512e5

It's cause a tick sync problem which in turn is crashing servers randomly.

**Comment by Robotia** [comment] 2016-01-18 18:57
@iKaneki-Ken How do you know that is the cause of the problem? Have you tried running the server without it yourself?

**Comment by Robotia** [comment] 2016-01-22 21:19
Update: Please see https://github.com/TCPR/KCauldron/releases for the latest builds.

Closing this thread.

**Closed by Robotia** 2016-01-22 21:19 UTC
