### ISSUE TITLE
Soulbound

### ISSUE THREAD

**Issue by TerdyTheTerd** [TCPR/KCauldron#39] opened 2016-01-28 10:25 UTC
I hate to be the person to bring this up, as I have brought it up several times on both Ars Magica and Kcauldron issue trackers. Last time I posted it Ars magica dev told me kcauldron needed to fix it, and kcauldron dev told me ars magica dev needed to fix it :/. What I think is going on is the event fired onPlayerDeath (where soulbound items get stored) and onPlayerRespawn (where stored items get placed back into players inventory) get modified in some way due to kcauldron. Look [here](https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/PlayerTracker.java) for the event tracker class of Ars magica, it contains the code for both onPlayerDeath and onPlayerRespawn, this issue has been around since I started using cauldron back when it first got DMCA'd and would really love to see it fixed finally. I did notice some code for dimension change, and noticed there was a 40 (either in ticks or milliseconds, not sure) delay for syncing the stored data. It should also be noted that soulbound does in fact work in the overworld, but in any other dim it does not work, so maybe there is something altering how player dimension changes are handled. Through my testing EnderIO soulbound enchant works just fine, so it might be worth looking at [this](https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/enchantment/EnchantmentSoulBound.java) From what I can tell if ars magica were to change their onPlayerDeath(EntityPlayer player) to onPlayerDeath(PlayerDropsEvent evt) it would work, I tried doing this manually but soon found it would require changing nearly the entire code for Ars magica soulbound to work with that. Greatly appreciate you working so hard on KCauldron, hopefully it can become mainstream someday.

**Comment by Robotia** [comment] 2016-01-29 01:23
@TerdyTheTerd Are you certain this works perfectly on Vanilla Forge?

And thank you for your support :smile:

**Comment by TerdyTheTerd** [comment] 2016-01-29 02:42
Sorry if the video isn't of greatest quality, but here I show both vanilla forge and Kcauldron (Release 10 from this repo) dying in the overworld with soulbound items and then dying in the nether with soulbound (it is not limited to the nether, but I didn't want to record every dimension) 

Kcauldron [Video](https://youtu.be/ckx3vCw6OtQ)

Forge [Video](https://www.youtube.com/watch?v=mIhEdKZmBss&feature=youtu.be)

I will be glad to help in anyway you need me to.

**Comment by iKaneki-Ken** [comment] 2016-01-29 03:19
Question, do you have OpenBlocks installed?

**Comment by TerdyTheTerd** [comment] 2016-01-29 05:14
Yes I do, but it was installed on both forge and kcauldron servers. Maybe their grave code conflicts with ars magica soulbound in the KCauldron environment?

**Comment by Robotia** [comment] 2016-01-29 05:23
@TerdyTheTerd Looking at the video again, I think this is related to #27. Has something to do with KCauldron not spawning player entities properly. I want you to try something for me, install KCauldron official build 152 and test this. If it works, then the problem is related to https://gitlab.prok.pw/KCauldron/KCauldron/commit/1817b56ba3dc54f9c7d6e3250f1139576854d3b4

**Comment by iKaneki-Ken** [comment] 2016-01-29 05:47
@TerdyTheTerd Yes OpenBlocks graves have been conflicting with enchantments like Soulbound for a while, we've talked to the dev, it's all up to when he wants to fix it.

**Comment by TerdyTheTerd** [comment] 2016-01-29 06:04
Alright, just tested on build 152 for forge 1492, issue is still present. I will update this post with results after removing openblocks from both server and client.

**Comment by Robotia** [comment] 2016-01-29 06:18
What if you spawn in the dimension you died in after death?

**Comment by TerdyTheTerd** [comment] 2016-01-29 07:26
I can confirm if I respawn in the same dimension that I died in soulbound items are in fact kept. Looks like a temp solution until this can be further sorted is to set a per world spawn point, then any player who dies will respawn in the same world and will not loose soulbound items anymore. Hopefully the fact that its across dimensions helps find what is causing this.

**Comment by KasperFranz** [comment] 2016-01-29 07:50
It's the same problem with Twillight forests Charm og keeping where you have to respawn in the same dimension (or relog).

The issue might be similair

**Comment by Robotia** [comment] 2016-01-29 11:56
Yea I feel like it has to do with improper teleportation...we'll see though.

**Comment by Robotia** [comment] 2016-01-29 19:34
@TerdyTheTerd I think I may have found the problem, but let me confirm with you first.
My Questions:
+ Do you have keepInventory on, or is this just something SoulBound does by default when you die?
+ This does not affect *other, more normal* enchants, correct?

**Comment by TerdyTheTerd** [comment] 2016-01-29 22:32
One of the devs over at Ars actually looked into it further, he thinks he found the issue [here](https://gitlab.prok.pw/KCauldron/KCauldron/issues/196). As for your questions, no keepInventory is off, the soulbound enchant is supposed to prevent players from loosing the item upon death. I don't think it has any debug options.

**Comment by Robotia** [comment] 2016-01-29 22:49
@TerdyTheTerd Yes, I noticed that there was that difference between KCauldron and MinecraftForge when I did fdd4959dd2d75cf56d2be4e2d68ce81c39888eef. That probably won't fix it though, I think he's right about line 616.

**Closed** 2016-01-30 22:43 UTC

**Comment by Robotia** [comment] 2016-01-31 06:44
@TerdyTheTerd Did Build 13 work for you?

**Comment by TerdyTheTerd** [comment] 2016-01-31 10:46
@Robotia You are my hero, as far I my test went soulbound items properly work now when going across dimensions, even from the end! This beckons for another donation, but I wonder do you prefer them over the Accretion server donation link or from patreon? Now if only we could multi-thread all the things :D

**Comment by Robotia** [comment] 2016-01-31 16:00
@TerdyTheTerd Thanks! And PayPal is preferable :)

**Comment by goreacraft** [comment] 2016-02-01 14:31
goreacraft buying you a coffee, donation incoming now

**Comment by Robotia** [comment] 2016-02-01 15:19
@goreacraft Thank you :smile:

**Comment by Robotia** [comment] 2016-02-01 22:37
@TerdyTheTerd Let me know if this issue reappears in B14 when it comes out.

**Comment by TerdyTheTerd** [comment] 2016-02-05 09:04
@Robotia Just tested on release 14 beta, soulbound still works like a charm. Didn't notice any issues, but I only tested for about 10 minutes, teleporting around dimensions, using enchantments, a few plugins, flying through the world and using a few machines (for TE testing). My very limited test showed all is well
